export const Y_SCALE_PADDING_MULTIPLIER = 1.1; // Adds 10% padding to top of Y axis
export const DEFAULT_Y_AXIS_TICKS = 5;
export const DEFAULT_X_AXIS_TICKS = 5;
export const BAR_WIDTH_RATIO = 0.8; // Width of bar relative to available space between bars
export const BAR_GAP = 2; // Gap between bars in pixels
export const BAR_ANIMATION_DURATION = 800;
export const BAR_ANIMATION_DELAY = 50;
export const BAR_OPACITY = 0.6;
export const BAR_HOVER_OPACITY = 1;
export const BAR_FINAL_OPACITY = 0.7;
export const BAR_BORDER_RADIUS = 2;
export const HOVER_ANIMATION_DURATION = 200;
export const HOVER_TRANSLATE_Y = -2;
export const GRADIENT_START_OPACITY = 0.7;
export const GRADIENT_END_OPACITY = 0.4;
